// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: schedule.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const clockIn = `-- name: ClockIn :one
UPDATE schedules
SET clock_in_at = NOW(),
    clock_in_lat = $2,
    clock_in_lng = $3,
    clock_in_verified = $4
WHERE id = $1
RETURNING id, client_name, start_at, end_at, location, latitude, longitude, clock_in_at, clock_in_lat, clock_in_lng, clock_out_at, clock_out_lat, clock_out_lng, created_at, updated_at, clock_in_verified, clock_out_verified
`

type ClockInParams struct {
	ID        int32
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	Verified  sql.NullBool
}

func (q *Queries) ClockIn(ctx context.Context, arg ClockInParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, clockIn,
		arg.ID,
		arg.Latitude,
		arg.Longitude,
		arg.Verified,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.ClockInAt,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutAt,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInVerified,
		&i.ClockOutVerified,
	)
	return i, err
}

const clockOut = `-- name: ClockOut :one
UPDATE schedules
SET clock_out_at = NOW(),
    clock_out_lat = $2,
    clock_out_lng = $3,
    clock_out_verified = $4
WHERE id = $1
RETURNING id, client_name, start_at, end_at, location, latitude, longitude, clock_in_at, clock_in_lat, clock_in_lng, clock_out_at, clock_out_lat, clock_out_lng, created_at, updated_at, clock_in_verified, clock_out_verified
`

type ClockOutParams struct {
	ID        int32
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	Verified  sql.NullBool
}

func (q *Queries) ClockOut(ctx context.Context, arg ClockOutParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, clockOut,
		arg.ID,
		arg.Latitude,
		arg.Longitude,
		arg.Verified,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.ClockInAt,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutAt,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInVerified,
		&i.ClockOutVerified,
	)
	return i, err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    client_name, start_at, end_at,
    location, latitude, longitude
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, client_name, start_at, end_at, location, latitude, longitude, clock_in_at, clock_in_lat, clock_in_lng, clock_out_at, clock_out_lat, clock_out_lng, created_at, updated_at, clock_in_verified, clock_out_verified
`

type CreateScheduleParams struct {
	ClientName string
	StartAt    time.Time
	EndAt      time.Time
	Location   string
	Latitude   sql.NullFloat64
	Longitude  sql.NullFloat64
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.ClientName,
		arg.StartAt,
		arg.EndAt,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.ClockInAt,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutAt,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInVerified,
		&i.ClockOutVerified,
	)
	return i, err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, client_name, start_at, end_at, location, latitude, longitude, clock_in_at, clock_in_lat, clock_in_lng, clock_out_at, clock_out_lat, clock_out_lng, created_at, updated_at, clock_in_verified, clock_out_verified FROM schedules
WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id int32) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByID, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.ClockInAt,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutAt,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInVerified,
		&i.ClockOutVerified,
	)
	return i, err
}

const getScheduleStats = `-- name: GetScheduleStats :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE clock_in_at IS NULL AND end_at < NOW())::int AS missed,
    COUNT(*) FILTER (WHERE clock_in_at IS NULL AND end_at > NOW() AND start_at >= $1::timestamptz AND start_at < $2::timestamptz)::int AS upcoming,
    COUNT(*) FILTER (WHERE clock_out_at IS NOT NULL AND start_at >= $1::timestamptz AND start_at < $2::timestamptz)::int AS completed
FROM schedules
`

type GetScheduleStatsParams struct {
	TodayStart time.Time
	TodayEnd   time.Time
}

type GetScheduleStatsRow struct {
	Total     int32
	Missed    int32
	Upcoming  int32
	Completed int32
}

func (q *Queries) GetScheduleStats(ctx context.Context, arg GetScheduleStatsParams) (GetScheduleStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getScheduleStats, arg.TodayStart, arg.TodayEnd)
	var i GetScheduleStatsRow
	err := row.Scan(
		&i.Total,
		&i.Missed,
		&i.Upcoming,
		&i.Completed,
	)
	return i, err
}

const getTodaySchedules = `-- name: GetTodaySchedules :many
SELECT id, client_name, start_at, end_at, location, latitude, longitude, clock_in_at, clock_in_lat, clock_in_lng, clock_out_at, clock_out_lat, clock_out_lng, created_at, updated_at, clock_in_verified, clock_out_verified FROM schedules
WHERE start_at >= $1::timestamptz AND start_at < $2::timestamptz
ORDER BY start_at ASC
`

type GetTodaySchedulesParams struct {
	TodayStart time.Time
	TodayEnd   time.Time
}

func (q *Queries) GetTodaySchedules(ctx context.Context, arg GetTodaySchedulesParams) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, getTodaySchedules, arg.TodayStart, arg.TodayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.StartAt,
			&i.EndAt,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.ClockInAt,
			&i.ClockInLat,
			&i.ClockInLng,
			&i.ClockOutAt,
			&i.ClockOutLat,
			&i.ClockOutLng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClockInVerified,
			&i.ClockOutVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, client_name, start_at, end_at, location, latitude, longitude, clock_in_at, clock_in_lat, clock_in_lng, clock_out_at, clock_out_lat, clock_out_lng, created_at, updated_at, clock_in_verified, clock_out_verified FROM schedules
ORDER BY start_at ASC
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.StartAt,
			&i.EndAt,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.ClockInAt,
			&i.ClockInLat,
			&i.ClockInLng,
			&i.ClockOutAt,
			&i.ClockOutLat,
			&i.ClockOutLng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClockInVerified,
			&i.ClockOutVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
