// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: task.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    schedule_id, title, status
) VALUES (
    $1, $2, 'pending'
)
RETURNING id, schedule_id, title, status, reason, created_at, updated_at
`

type CreateTaskParams struct {
	ScheduleID int32
	Title      string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.ScheduleID, arg.Title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.Title,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, schedule_id, title, status, reason, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.Title,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByScheduleID = `-- name: GetTasksByScheduleID :many
SELECT id, schedule_id, title, status, reason, created_at, updated_at FROM tasks
WHERE schedule_id = $1
ORDER BY id ASC
`

func (q *Queries) GetTasksByScheduleID(ctx context.Context, scheduleID int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByScheduleID, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.Title,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2,
    reason = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, schedule_id, title, status, reason, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     int32
	Status string
	Reason sql.NullString
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status, arg.Reason)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.Title,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
