// Code generated by MockGen. DO NOT EDIT.
// Source: schedule.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "bht-test/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIScheduleUsecase is a mock of IScheduleUsecase interface.
type MockIScheduleUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIScheduleUsecaseMockRecorder
}

// MockIScheduleUsecaseMockRecorder is the mock recorder for MockIScheduleUsecase.
type MockIScheduleUsecaseMockRecorder struct {
	mock *MockIScheduleUsecase
}

// NewMockIScheduleUsecase creates a new mock instance.
func NewMockIScheduleUsecase(ctrl *gomock.Controller) *MockIScheduleUsecase {
	mock := &MockIScheduleUsecase{ctrl: ctrl}
	mock.recorder = &MockIScheduleUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScheduleUsecase) EXPECT() *MockIScheduleUsecaseMockRecorder {
	return m.recorder
}

// ClockIn mocks base method.
func (m *MockIScheduleUsecase) ClockIn(ctx context.Context, id int32, req domain.ClockInRequest) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClockIn", ctx, id, req)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClockIn indicates an expected call of ClockIn.
func (mr *MockIScheduleUsecaseMockRecorder) ClockIn(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClockIn", reflect.TypeOf((*MockIScheduleUsecase)(nil).ClockIn), ctx, id, req)
}

// ClockOut mocks base method.
func (m *MockIScheduleUsecase) ClockOut(ctx context.Context, id int32, req domain.ClockOutRequest) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClockOut", ctx, id, req)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClockOut indicates an expected call of ClockOut.
func (mr *MockIScheduleUsecaseMockRecorder) ClockOut(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClockOut", reflect.TypeOf((*MockIScheduleUsecase)(nil).ClockOut), ctx, id, req)
}

// Create mocks base method.
func (m *MockIScheduleUsecase) Create(ctx context.Context, req domain.CreateScheduleRequest) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIScheduleUsecaseMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIScheduleUsecase)(nil).Create), ctx, req)
}

// GetByID mocks base method.
func (m *MockIScheduleUsecase) GetByID(ctx context.Context, id int32) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIScheduleUsecaseMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIScheduleUsecase)(nil).GetByID), ctx, id)
}

// GetStats mocks base method.
func (m *MockIScheduleUsecase) GetStats(ctx context.Context, timezone string) (*domain.ScheduleStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, timezone)
	ret0, _ := ret[0].(*domain.ScheduleStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockIScheduleUsecaseMockRecorder) GetStats(ctx, timezone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockIScheduleUsecase)(nil).GetStats), ctx, timezone)
}

// GetToday mocks base method.
func (m *MockIScheduleUsecase) GetToday(ctx context.Context, timezone string) ([]*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToday", ctx, timezone)
	ret0, _ := ret[0].([]*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToday indicates an expected call of GetToday.
func (mr *MockIScheduleUsecaseMockRecorder) GetToday(ctx, timezone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToday", reflect.TypeOf((*MockIScheduleUsecase)(nil).GetToday), ctx, timezone)
}

// List mocks base method.
func (m *MockIScheduleUsecase) List(ctx context.Context) ([]*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIScheduleUsecaseMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIScheduleUsecase)(nil).List), ctx)
}
