// Code generated by MockGen. DO NOT EDIT.
// Source: task.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "bht-test/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITaskUsecase is a mock of ITaskUsecase interface.
type MockITaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockITaskUsecaseMockRecorder
}

// MockITaskUsecaseMockRecorder is the mock recorder for MockITaskUsecase.
type MockITaskUsecaseMockRecorder struct {
	mock *MockITaskUsecase
}

// NewMockITaskUsecase creates a new mock instance.
func NewMockITaskUsecase(ctrl *gomock.Controller) *MockITaskUsecase {
	mock := &MockITaskUsecase{ctrl: ctrl}
	mock.recorder = &MockITaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskUsecase) EXPECT() *MockITaskUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITaskUsecase) Create(ctx context.Context, req domain.CreateTaskRequest) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITaskUsecaseMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITaskUsecase)(nil).Create), ctx, req)
}

// UpdateStatus mocks base method.
func (m *MockITaskUsecase) UpdateStatus(ctx context.Context, id int32, req domain.UpdateTaskRequest) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, req)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockITaskUsecaseMockRecorder) UpdateStatus(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockITaskUsecase)(nil).UpdateStatus), ctx, id, req)
}
