// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Blue Horn Tech",
            "email": "hr@bluehorntek.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/schedules": {
            "get": {
                "description": "Get a list of all caregiver schedules ordered by date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "List all schedules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/bht-test_internal_domain.Schedule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new schedule along with its associated tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Create a new schedule",
                "parameters": [
                    {
                        "description": "Schedule and tasks details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.CreateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bht-test_internal_domain.Schedule"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/stats": {
            "get": {
                "description": "Get dashboard statistics relative to user timezone",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedule statistics",
                "parameters": [
                    {
                        "type": "string",
                        "default": "UTC",
                        "description": "User timezone (e.g. Asia/Tokyo)",
                        "name": "X-Timezone",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bht-test_internal_domain.ScheduleStats"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/today": {
            "get": {
                "description": "Get all schedules for the current date relative to user timezone",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get today's schedules",
                "parameters": [
                    {
                        "type": "string",
                        "default": "UTC",
                        "description": "User timezone (e.g. Asia/Tokyo)",
                        "name": "X-Timezone",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/bht-test_internal_domain.Schedule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/{id}": {
            "get": {
                "description": "Get a single schedule with its associated care tasks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedule by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bht-test_internal_domain.Schedule"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/{id}/clock-in": {
            "post": {
                "description": "Start a visit by recording timestamp and geolocation. Schedule must be in 'upcoming' status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Clock in (start visit)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Geolocation coordinates",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ClockInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bht-test_internal_domain.Schedule"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/{id}/clock-out": {
            "post": {
                "description": "End a visit by recording timestamp and geolocation. Schedule must be in 'in_progress' status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Clock out (end visit)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Geolocation coordinates",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ClockOutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bht-test_internal_domain.Schedule"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "post": {
                "description": "Create a new care task associated with a specific schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Add task to schedule",
                "parameters": [
                    {
                        "description": "Task details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bht-test_internal_domain.Task"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{taskId}/update": {
            "post": {
                "description": "Mark a care activity as completed or not_completed. If not_completed, a reason is required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Update task status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status and optional reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.UpdateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/bht-test_internal_domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bht-test_internal_domain.Task"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bht-test_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bht-test_internal_domain.ClockInRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                }
            }
        },
        "bht-test_internal_domain.ClockOutRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                }
            }
        },
        "bht-test_internal_domain.CreateScheduleRequest": {
            "type": "object",
            "required": [
                "client_name",
                "end_at",
                "latitude",
                "location",
                "longitude",
                "start_at"
            ],
            "properties": {
                "client_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "end_at": {
                    "type": "string",
                    "example": "2026-03-06T18:00:00+09:00"
                },
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90,
                    "example": 35.6895
                },
                "location": {
                    "type": "string",
                    "example": "Tokyo Branch"
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180,
                    "example": 139.6917
                },
                "start_at": {
                    "type": "string",
                    "example": "2026-03-06T10:00:00+09:00"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bht-test_internal_domain.CreateTaskRequest"
                    }
                }
            }
        },
        "bht-test_internal_domain.CreateTaskRequest": {
            "type": "object",
            "required": [
                "schedule_id",
                "title"
            ],
            "properties": {
                "schedule_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "bht-test_internal_domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "bht-test_internal_domain.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "bht-test_internal_domain.Schedule": {
            "type": "object",
            "properties": {
                "client_name": {
                    "type": "string"
                },
                "clock_in_at": {
                    "type": "string"
                },
                "clock_in_lat": {
                    "type": "number"
                },
                "clock_in_lng": {
                    "type": "number"
                },
                "clock_in_verified": {
                    "type": "boolean"
                },
                "clock_out_at": {
                    "type": "string"
                },
                "clock_out_lat": {
                    "type": "number"
                },
                "clock_out_lng": {
                    "type": "number"
                },
                "clock_out_verified": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "end_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "start_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bht-test_internal_domain.Task"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "bht-test_internal_domain.ScheduleStats": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "missed": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "upcoming": {
                    "type": "integer"
                }
            }
        },
        "bht-test_internal_domain.Task": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "schedule_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "bht-test_internal_domain.UpdateTaskRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "completed",
                        "not_completed"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Mini EVV Logger API",
	Description:      "Caregiver Shift Tracker API for Electronic Visit Verification (EVV) compliance.\nCaregivers can view schedules, clock in/out with geolocation, and track care activity progress.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
