// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	sqlc "bht-test/internal/repository/sqlc"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// ClockIn mocks base method.
func (m *MockIRepository) ClockIn(ctx context.Context, arg sqlc.ClockInParams) (sqlc.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClockIn", ctx, arg)
	ret0, _ := ret[0].(sqlc.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClockIn indicates an expected call of ClockIn.
func (mr *MockIRepositoryMockRecorder) ClockIn(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClockIn", reflect.TypeOf((*MockIRepository)(nil).ClockIn), ctx, arg)
}

// ClockOut mocks base method.
func (m *MockIRepository) ClockOut(ctx context.Context, arg sqlc.ClockOutParams) (sqlc.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClockOut", ctx, arg)
	ret0, _ := ret[0].(sqlc.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClockOut indicates an expected call of ClockOut.
func (mr *MockIRepositoryMockRecorder) ClockOut(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClockOut", reflect.TypeOf((*MockIRepository)(nil).ClockOut), ctx, arg)
}

// CreateSchedule mocks base method.
func (m *MockIRepository) CreateSchedule(ctx context.Context, arg sqlc.CreateScheduleParams) (sqlc.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, arg)
	ret0, _ := ret[0].(sqlc.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockIRepositoryMockRecorder) CreateSchedule(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockIRepository)(nil).CreateSchedule), ctx, arg)
}

// CreateTask mocks base method.
func (m *MockIRepository) CreateTask(ctx context.Context, arg sqlc.CreateTaskParams) (sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, arg)
	ret0, _ := ret[0].(sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockIRepositoryMockRecorder) CreateTask(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockIRepository)(nil).CreateTask), ctx, arg)
}

// GetScheduleByID mocks base method.
func (m *MockIRepository) GetScheduleByID(ctx context.Context, id int32) (sqlc.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleByID indicates an expected call of GetScheduleByID.
func (mr *MockIRepositoryMockRecorder) GetScheduleByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleByID", reflect.TypeOf((*MockIRepository)(nil).GetScheduleByID), ctx, id)
}

// GetScheduleStats mocks base method.
func (m *MockIRepository) GetScheduleStats(ctx context.Context, arg sqlc.GetScheduleStatsParams) (sqlc.GetScheduleStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleStats", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetScheduleStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleStats indicates an expected call of GetScheduleStats.
func (mr *MockIRepositoryMockRecorder) GetScheduleStats(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleStats", reflect.TypeOf((*MockIRepository)(nil).GetScheduleStats), ctx, arg)
}

// GetTaskByID mocks base method.
func (m *MockIRepository) GetTaskByID(ctx context.Context, id int32) (sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockIRepositoryMockRecorder) GetTaskByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockIRepository)(nil).GetTaskByID), ctx, id)
}

// GetTasksByScheduleID mocks base method.
func (m *MockIRepository) GetTasksByScheduleID(ctx context.Context, scheduleID int32) ([]sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByScheduleID", ctx, scheduleID)
	ret0, _ := ret[0].([]sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByScheduleID indicates an expected call of GetTasksByScheduleID.
func (mr *MockIRepositoryMockRecorder) GetTasksByScheduleID(ctx, scheduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByScheduleID", reflect.TypeOf((*MockIRepository)(nil).GetTasksByScheduleID), ctx, scheduleID)
}

// GetTodaySchedules mocks base method.
func (m *MockIRepository) GetTodaySchedules(ctx context.Context, arg sqlc.GetTodaySchedulesParams) ([]sqlc.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodaySchedules", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodaySchedules indicates an expected call of GetTodaySchedules.
func (mr *MockIRepositoryMockRecorder) GetTodaySchedules(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodaySchedules", reflect.TypeOf((*MockIRepository)(nil).GetTodaySchedules), ctx, arg)
}

// ListSchedules mocks base method.
func (m *MockIRepository) ListSchedules(ctx context.Context) ([]sqlc.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx)
	ret0, _ := ret[0].([]sqlc.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockIRepositoryMockRecorder) ListSchedules(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockIRepository)(nil).ListSchedules), ctx)
}

// UpdateTaskStatus mocks base method.
func (m *MockIRepository) UpdateTaskStatus(ctx context.Context, arg sqlc.UpdateTaskStatusParams) (sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockIRepositoryMockRecorder) UpdateTaskStatus(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockIRepository)(nil).UpdateTaskStatus), ctx, arg)
}

// WithTx mocks base method.
func (m *MockIRepository) WithTx(tx *sql.Tx) *sqlc.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*sqlc.Queries)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockIRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockIRepository)(nil).WithTx), tx)
}
